all: sample2D

sample2D: Sample_GL3_2D.cpp glad.c
	g++ -o sample2D Sample_GL3_2D.cpp glad.c -lGL -lglfw -lftgl -lSOIL -I/usr/local/include -I/usr/local/include/freetype2 -L/usr/local/lib

clean:
	rm sample2D

alias gamer="g++ -o game game.cpp glad.c -lGL -lglfw -lftgl -lSOIL -ldl -I/usr/include/freetype2 -I/usr/include -I"irrklang/include" -I"/usr/lib" irrklang/bin/linux-gcc-64/libIrrKlang.so -Lirrklang/bin/dotnet-4-64/ikpMP3.dll -pthread"
